### ISSUE TITLE
Inconsistencies after rebasing binary

### ISSUE THREAD

**Issue by face0xff** [thalium/symless#38]
In pre-analysis mode, symless will name fields and create repeatable comments based on the binary's base address (and probably many more things are based on it).

Once the database is created, rebasing it will create many inconsistencies (e.g. method names in vtable structures show the wrong address). This is especially annoying for repeatable comments which should automatically link to functions (for instance, repeatable comments that link to implementation candidates for vtable methods).

Not a bug per se, but maybe it would be nice to have a feature (like a command line option) to tell symless to automatically rebase binaries to 0x0 during pre-analysis?

**Comment by anOtherAnalyse** [comment]
Fixed in 5b7247a3883098ef5ce0dc2c552bbfeb4226f0af.
Added a new key `"rebase_db"` in `config.json`. It defaults to `true`. When enabled, the database will be rebased to 0 before applying any changes.
