### ISSUE TITLE
Unable to use on IDA Pro 8.4

### ISSUE THREAD

**Issue by ChinaNuke** [thalium/symless#44]
I copied the symless directory and the symless.py to /opt/idapro-8.4/plugins, and then when I launch IDA Pro I get the following error, and there is no "symless" entry in the "Edit" -> "Plugins" menu.

```
/opt/idapro-8.4/plugins/symless.py: undefined function __plugins__symless.PLUGIN_ENTRY
```

**Comment by anOtherAnalyse** [comment]
Try copying the [symless_plugin.py](../blob/main/plugin/symless_plugin.py) file instead of the symless.py file.

**Comment by ChinaNuke** [comment]
Sorry I copied the wrong file, thank you for pointing it out. 😃
